display_name: PayID
package_name: PayID
maintainer:
  name: Kaung Khant Kyaw
  email: kaungkhantjc@gmail.com
priority: optional
section: x11
installed_size: 10000
essential: false
icon: assets/icon/icon-512.png

keywords:
  - Pay ID
  - KBZPay Transaction ID
  - WavePay Transaction ID

generic_name: PayID

categories:
  - Utility

startup_notify: true
# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/pay_id.metainfo.xml